### ISSUE TITLE
5.1 Improve the loads-broker for basic QA requirements

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#14]
Document and implement QA requirements for consistent load-test running with metric capturing.

**Comment by rpappalax** [comment]
Ensure the following loads-broker fixes/enhancements are completed
- [ ] loads/loads-broker#44
- [ ] loads/loads-broker#54
- [x] loads/loads-broker#48
- [ ] loads/loads-broker#69
- [x] loads/loads-broker#71

Complete formal autopush testplan in testrail which includes (current) connection threshold / node.

@bbangert what other metrics would be useful to you to track over time?

**Comment by pjenvey** [comment]
Removed #70 & #72 (goes w/ okr 5.3)
