### ISSUE TITLE
5.2 Regularly run automated load-testing

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#15]
Our load-tests should be run regularly on a schedule.

**Comment by rpappalax** [comment]
Loadtests will run by the fx-test team at the following times:

AUTOMATED

[1]. run basic ap-loadtester scenario 1x on commits (travis?)
[2]. run all ap-loadtest scenarios at STAGE deploy time (services-ops-pipeline)

MANUAL

[1]. For application instance "sizing" (together w/ Ops)
[2]. Ad-hoc: for more in-depth testing requiring larger resources (i.e. large connection test) or co-ordination w/ Ops

**Comment by pjenvey** [comment]
- [ ] loads/loads-broker#87
- [ ] loads/loads-broker#88
- [ ] loads/loads-broker#89
- [ ] mozilla-services/push-okr#16
