### ISSUE TITLE
5.3 Have database of historical load-test results

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#16]
For future regression testing, we should begin recording load-test results in a database.

**Comment by pjenvey** [comment]
- [ ] loads/loads-broker#69
- [ ] loads/loads-broker#70
- [ ] mozilla-services/push-okr#15
