### ISSUE TITLE
4.1 Dashboard created that shows the metrics described on Issue 56. Uptime Dashboard 

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#36]
Parent ticket for this issue: mozilla-services/push-service#56

Individual dashboards:
- [ ] mozilla-services/push-service#64
- [ ] mozilla-services/push-service#65
- [ ] mozilla-services/push-service#66
- [x] mozilla-services/autopush#874
- [x] mozilla-services/autopush#882

**Comment by bbangert** [comment]
Parent ticket for this issue: mozilla-services/push-service#56
