### ISSUE TITLE
1.1 Rust connection node productized

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#49]
Issues:

- [x] mozilla-services/autopush#1002
- [ ] mozilla-services/autopush#1045
- [ ] mozilla-services/autopush#1054
- [x] mozilla-services/autopush#1055
- [ ] mozilla-services/autopush#1060
- [ ] mozilla-services/autopush#1062
- [x] mozilla-services/autopush#1063
- [x] mozilla-services/autopush#1066
- [ ] mozilla-services/autopush#1090
