### ISSUE TITLE
1.2 All remaining Rust connection node issues from previous quarter have been closed.

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#55]
Issues:

- [x] mozilla-services/autopush#1002
- [x] mozilla-services/autopush#1054
- [x] mozilla-services/autopush#1055
- [x] mozilla-services/autopush#1060
- [x] mozilla-services/autopush#1062
- [x] mozilla-services/autopush#1063
- [x] mozilla-services/autopush#1066
- [x] mozilla-services/autopush#1090
- [x] mozilla-services/autopush#1121
- [x] mozilla-services/autopush#1133
