### ISSUE TITLE
3.1 High volume authenticated endpoint

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-okr#8]
Deployed to stage environment with load-testing results.

**Comment by pjenvey** [comment]
Dependencies:

- [x] loads/loads-broker#64
- [x] mozilla-services/ap-loadtester#75
- [x] mozilla-services/ap-loadtester#79
- [x] mozilla-services/autopush/issues/761
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1283231
